### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Ben10225**
http://beebeb.ddnsking.com:3000/
b@b
b123

Hello Teacher PengPeng
Are you feel better now?
Here is my Pr and I have updated some features.
And I left an account which has some history orders already.
Hope your body feel good ~~

### CODE REVIEW

**Comment by Ben10225** [comment]
I found that there is an interesting stuff,
when I open a google normal mode window to member page,
the page will send request to s3, and always shows CORS error even I had added prevent CORS header,
but
if I open f12 and do the same thing,
it wont show CORS error,
or if I use google incognito mode to get member page without f12,
it wont show error, too.

**Review by cwpeng — APPROVED** [review]
I feel good. Thanks for your caring.

I think you have done a wonderful job in this project. Let it go, and take next impossible mission for yourself. :)

**Comment by cwpeng** [comment]
We usually use public URL in S3 in `` or `<video>` or CSS styling, not by fetch(). So, I think CORS issue may not block our way to the goal we want to achieve?

**Comment by Ben10225** [comment]
彭彭好
我是從後端拿到一個授權對該圖片操作的 url 丟到前端
從前端 fetch 後會拿到該圖片的網址
不過總之那個神奇 bug 現在好像消失了
只存在那段時間我的 chrome 一般模式 (不開啟 f12 的狀態)
其他同學那時測試 或是我用其他瀏覽器 也是沒問題
我會再繼續加油～

**祝老師新年快樂！**

**Comment by cwpeng** [comment]
Happy new year. :)

**Pull request merged**
