### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Ben10225**
This is my codes for week1's assignments in lv2.
My discord name is BenPoN.
Tks teacher PengPeng !

http://44.227.116.145:3000/api/attractions?page=1
http://44.227.116.145:3000/api/attractions?page=0&keyword=藝文館所
http://44.227.116.145:3000/api/attractions?page=0&keyword=北
http://44.227.116.145:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
There should be some data in http://44.227.116.145:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80

**Comment by Ben10225** [comment]
I have fixed the problem.
Please read again.
Tks teacher PengPeng !

http://44.227.116.145:3000/api/attractions?page=1
http://44.227.116.145:3000/api/attractions?page=0&keyword=藝文館所
http://44.227.116.145:3000/api/attractions?page=0&keyword=北
http://44.227.116.145:3000/api/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But please fix issue below and re-request review again.

We nerver use SQL like this `SELECT * FROM attractions`. It's much better to use `LIMIT` in SQL to do pagination than do it in your own code.

**Comment by Ben10225** [comment]
I have revised the pagination data syntax.
Please check again.
Tks teacher PengPeng !

http://44.227.116.145:3000/api/attractions?page=1
http://44.227.116.145:3000/api/attractions?page=0&keyword=藝文館所
http://44.227.116.145:3000/api/attractions?page=0&keyword=北
http://44.227.116.145:3000/api/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done. You are in the first five. :)

**Comment by Ben10225** [comment]
Thank you teacher Pengpeng ~

**Pull request merged**
