### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Ben10225**
Here's my code for the assignment this week,
I also make regularizer about my database,
Tks teacher Pengpeng !

http://52.43.201.161:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Next page number should depend on API response, not just plus 1.

**Comment by Ben10225** [comment]
I have fixed the feedback problems,
please check again !
tks teacher Pengpeng !

**Comment by Ben10225** [comment]
I have fixed the feedback problems,
please check again !
tks teacher Pengpeng !

http://52.43.201.161:3000/

**Comment by Ben10225** [comment]
I have fixed the feedback problems,
and also revised some sql syntaxs,
please check again !
tks teacher Pengpeng !

http://52.43.201.161:3000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
